# Generated by Django 5.2 on 2025-05-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('rating', models.FloatField()),
                ('genre', models.CharField(choices=[('drama', 'Драма'), ('comedy', 'Комедия'), ('action', 'Экшн'), ('history', 'Тарихи'), ('fantasy', 'Фантастика')], max_length=20)),
                ('desc', models.TextField(blank=True)),
            ],
        ),
    ]
